name: Build website

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: docker://pandoc/core:3.6-ubuntu
      options: --entrypoint=sh
    steps:

      - name: Install dependencies
        run: apt update && apt install -y git make m4

      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Copy custom domain name configuration
        run: cp CNAME output/public/

      - name: Store generated content
        uses: actions/upload-artifact@v4
        with:
          path: output/public
          name: website

      - name: Store generated content for GH pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/public

  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
